/**
 * @nextship/cli: Dockerfile and ignore file rendering
 *
 * Everything that runs inside the image build is described here. The build
 * itself happens in Docker, on the platform the image runs on, so traces,
 * native binaries and lockfile resolution are all correct by construction.
 *
 * Three stages:
 *   builder   installs, runs `next build` with the adapter, prunes to /out
 *   manifest  a scratch image holding only manifest.json, exported to disk
 *   runtime   tini, node, the pruned tree, a non-root user
 *
 * Author: Gowtham
 * Design: ../../../../docs/00-design.md §7
 */

import type { PackageManager, ProjectInfo } from '../detect.js'

/** Next.js's default. The launcher reads PORT, so the platform can override it. */
export const CONTAINER_PORT = 3000

/**
 * The image is always built for the deployment target, never for the developer's
 * machine. Both AWS and DigitalOcean run amd64 by default, and an arm64 image
 * fails there at deploy time rather than build time.
 */
export const TARGET_PLATFORM = 'linux/amd64'

/** Secret ids, shared between the Dockerfile and the `docker build` arguments. */
export const KEY_SECRET_ID = 'nextship_key'
export const envSecretId = (index: number): string => `nextship_env_${index}`

/** Where the CLI writes the files the build needs, relative to the app root. */
export const BUILD_DIR = '.nextship/build'
/** Where the exported manifest lands, relative to the app root. */
export const OUTPUT_DIR = '.nextship/output'

export type BuildTarget = 'manifest' | 'runtime'

export function renderDockerfile(project: ProjectInfo): string {
  const workspace = project.appDir !== '.'
  // The app keeps its position relative to the workspace root, so traces that
  // reach above it (`../../node_modules/...`) resolve inside the image too.
  const appPath = workspace ? `/src/${project.appDir}` : '/src'
  const cache = CACHES[project.packageManager]

  const envMounts = project.envFiles.map(
    (file, index) => `--mount=type=secret,id=${envSecretId(index)},target=${appPath}/${file}`
  )

  return [
    // Enables secret and cache mounts. Docker pulls the frontend on first use.
    '# syntax=docker/dockerfile:1',
    '# Generated by nextship. Do not edit; changes are overwritten on every build.',
    '# Rationale for each instruction: docs/00-design.md §7',
    '',
    `FROM node:${project.nodeMajor}-slim AS builder`,
    'WORKDIR /src',
    `ENV NEXT_TELEMETRY_DISABLED=1 ${cache.env}=${cache.dir}`,
    'RUN corepack enable',
    // Manifests before sources, so editing a component does not re-run the
    // install. Measured on a real project: the install is 97 s and the compile is
    // 6 s, so copying everything first made every one-character change cost the
    // install again. `--parents` preserves directory structure, which is what
    // makes a workspace's nested manifests land in the right places.
    `COPY --parents ${manifestSources(project).join(' ')} ./`,
    // Every dependency, including devDependencies, because the build needs them.
    // The store is a cache mount, so repeat builds only download what changed.
    `RUN --mount=type=cache,id=nextship-${project.packageManager},target=${cache.dir} ${installCommand(project)}`,
    // The application, on top of the installed dependencies. node_modules is
    // excluded from the context, so this cannot overwrite what the install produced.
    'COPY . .',
    `WORKDIR ${appPath}`,
    // Declared after the install so a new deployment id never invalidates it.
    'ARG NEXTSHIP_DEPLOYMENT_ID',
    `ENV NEXTSHIP_DEPLOYMENT_ID=$NEXTSHIP_DEPLOYMENT_ID NEXT_ADAPTER_PATH=${appPath}/${BUILD_DIR}/adapter.mjs`,
    // The encryption key and any env files are mounted for this step only, so
    // neither can end up in an image layer. Next.js reads the env files from
    // disk exactly as it would on the developer's machine.
    [
      `RUN --mount=type=secret,id=${KEY_SECRET_ID}`,
      // Next.js's own incremental build cache. Without it every source change is
      // a cold build: measured at 145 s against 19 s for no change. It is a cache
      // mount rather than a copied directory, so it never enters a layer, and the
      // prune step runs in a later RUN where the mount no longer exists.
      `--mount=type=cache,id=nextship-next-${project.name},target=${appPath}/.next/cache`,
      ...envMounts,
      `NEXT_SERVER_ACTIONS_ENCRYPTION_KEY="$(cat /run/secrets/${KEY_SECRET_ID})"`,
      project.buildCommand.join(' '),
    ].join(' '),
    `RUN node ${BUILD_DIR}/prune.cjs /src ${project.appDir} /out`,
    '',
    'FROM scratch AS manifest',
    `COPY --from=builder ${appPath}/${OUTPUT_DIR}/manifest.json /manifest.json`,
    '',
    `FROM node:${project.nodeMajor}-slim AS runtime`,
    `WORKDIR ${appPath}`,
    // tini gives the container a PID 1 that forwards SIGTERM to node, so
    // in-flight requests and after() callbacks finish on shutdown. jemalloc is
    // the allocator Next.js documents for sharp on glibc, where the default one
    // grows without bound under sustained image optimization. npm and corepack
    // are removed because nothing in the runtime uses them.
    'RUN apt-get update' +
      ' && apt-get install -y --no-install-recommends tini libjemalloc2' +
      ' && rm -rf /var/lib/apt/lists/*' +
      ' && rm -rf /usr/local/lib/node_modules /usr/local/bin/npm /usr/local/bin/npx /usr/local/bin/corepack',
    // Created before the copy so ownership is set by COPY itself. A chown -R
    // afterwards would duplicate every file into a second layer.
    'RUN groupadd --system app && useradd --system --gid app app',
    'COPY --from=builder --chown=app:app /out /src',
    // Next.js writes ISR entries and optimized images here at runtime.
    'RUN mkdir -p .next/cache && chown app:app .next/cache',
    'USER app',
    `ENV NODE_ENV=production PORT=${CONTAINER_PORT} HOSTNAME=0.0.0.0 NEXT_TELEMETRY_DISABLED=1` +
      ' LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2',
    `EXPOSE ${CONTAINER_PORT}`,
    // A HEAD request, so the check costs no response body. Anything below 500
    // means the server is up; a 404 at / is still a healthy server.
    'HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3' +
      ` CMD node -e "fetch('http://127.0.0.1:'+process.env.PORT+'/',{method:'HEAD'})` +
      `.then(r=>process.exit(r.status<500?0:1)).catch(()=>process.exit(1))"`,
    'ENTRYPOINT ["/usr/bin/tini", "--"]',
    'CMD ["node", "server.cjs"]',
    '',
  ].join('\n')
}

/**
 * Keeps everything the build does not need out of the context. The rules are
 * deny-list shaped because the build needs the source tree, and the user's own
 * .dockerignore is appended so its rules still apply.
 */
export function renderDockerignore(project: ProjectInfo): string {
  const prefix = project.appDir === '.' ? '' : `${project.appDir}/`
  const lines = ['# Generated by nextship. Do not edit; changes are overwritten on every build.']

  // The project's rules come first and ours last, because Docker resolves
  // conflicts by last match. Ordered the other way, a project rule such as
  // `!.env` would re-include the files that are supposed to reach the build only
  // as secret mounts.
  if (project.userDockerignore) {
    lines.push('', '# Rules from the project .dockerignore', project.userDockerignore.trimEnd())
  }

  lines.push(
    '',
    '# nextship rules, last so the rules above cannot undo them.',
    // Installed inside the image for the platform it runs on.
    '**/node_modules',
    '**/.git',
    // The builder compiles its own; a host .next is the wrong platform.
    '**/.next',
    // Holds the Server Actions key. Only the build helpers are let through.
    '**/.nextship',
    `!${prefix}${BUILD_DIR}`,
    // Mounted as build secrets instead, so they never enter a layer.
    '**/.env',
    '**/.env.*'
  )

  return lines.join('\n') + '\n'
}

/**
 * Everything the install reads, and nothing else. A workspace also needs every
 * sibling manifest, which the recursive glob collects; a single package has no
 * nested manifests, and a glob that matches nothing would fail the build.
 */
function manifestSources(project: ProjectInfo): string[] {
  return [
    ...(project.appDir === '.' ? [] : ['**/package.json']),
    'package.json',
    ...(project.lockfile ? [project.lockfile] : []),
    ...project.installerConfigs,
  ]
}

/** Cache location per package manager, set through the variable each one honours. */
const CACHES: Record<PackageManager, { env: string; dir: string }> = {
  pnpm: { env: 'npm_config_store_dir', dir: '/cache/pnpm' },
  npm: { env: 'npm_config_cache', dir: '/cache/npm' },
  yarn: { env: 'YARN_CACHE_FOLDER', dir: '/cache/yarn' },
  bun: { env: 'BUN_INSTALL_CACHE_DIR', dir: '/cache/bun' },
}

/** A frozen install where a lockfile exists, so the image resolves what the developer resolved. */
function installCommand(project: ProjectInfo): string {
  const frozen: Record<PackageManager, string> = {
    npm: 'npm ci --no-audit --no-fund',
    pnpm: 'pnpm install --frozen-lockfile',
    yarn: 'yarn install --frozen-lockfile',
    bun: 'bun install --frozen-lockfile',
  }
  const loose: Record<PackageManager, string> = {
    npm: 'npm install --no-audit --no-fund',
    pnpm: 'pnpm install',
    yarn: 'yarn install',
    bun: 'bun install',
  }
  return (project.lockfile ? frozen : loose)[project.packageManager]
}
